### PR TITLE
Complete LastUser implementation

### PR DESCRIPTION
**Pull request by coczero**
Complete last.fm user.getInfo api implemented.
Wasn't sure if 'bootstrap' is a bool, therefore I left it as an int.
Maybe 'User' could be an enum?
Also fields private because it doesnt really make sense that they can be set. I think it would be optimal for them to be readonly.

### CODE REVIEW

**Comment by rikkit** [comment]
Hi @coczero, I've been busy this week! I'll try get this in ASAP. Code looks ok to me at a glance though. Thanks!

**Comment by coczero** [comment]
I just noticed the tabs are still a bit off.
I use different tabs at work, could you tell me your tab settings? :)

**Comment by rikkit** [comment]
The project uses the default VS settings, which IIRC is 4 spaces instead of a tab. If you're updating tabs can you merge your commits as well? :) I'll make some time to merge this this evening.

**Comment by coczero** [comment]
I am new to all this git stuff and I tried to squash or merge these commits, but I have no idea how haha.

**Comment by coczero** [comment]
Is this ok now?

**Comment by rikkit** [comment]
Hi @coczero, so sorry I haven't made enough time to merge this. Last time I sat down and ended up having to update VS :/ . I'll push out a new release tonight. BTW are you using v1.0.x (.net standard) or v0.3.x (pcl 259) in your project?

**Comment by coczero** [comment]
No worries. :) 
I use the v1.0.x in my project.

**Comment by rikkit** [comment]
Hi @coczero , this is now released on Nuget. Thanks, and again sorry for the delay :)

**Pull request merged**
