### PR TITLE
Add stats

### PR DESCRIPTION
**Pull request by bbougot**
Add stats to LastArtist

### CODE REVIEW

**Comment by bbougot** [comment]
Could it be possible to ship it into Nuget?

**Comment by rikkit** [comment]
LGTM. I'll update the public NuGet soon, but you can switch to the [prerelease NuGet ](https://github.com/inflatablefriends/lastfm#nuget---prerelease-code) until that happens

Cheers

**Comment by rikkit** [comment]
@bbougot this has just gone into [v0.2.2](https://github.com/inflatablefriends/lastfm/releases/tag/v0.2.2)

**Comment by bbougot** [comment]
Great thanks!

**Pull request merged**
