### PR TITLE
Fix packaging for Inflatable.Lastfm.SQLite and update dependencies

### LINKED ISSUE #115: Update SQLite package to .Net Standard
The package target doesn't look right: https://github.com/Qstick/lastfm/blob/38967fdc73090b93e1b3d809250fb64bfdcc779f/.nuget/Inflatable.Lastfm.SQLite.nuspec#L22

### LINKED ISSUE #122: TypeLoadException problem with SQLite scrobbler
Since the new update the SQLite scrobbler is not working anymore.
I get the following error message:
`TypeLoadException: The method "RemoveFromCacheAsync" of type "IF.Lastfm.SQLite.SQLiteScrobbler" of assembly "IF.Lastfm.SQLite, Version=0.2.0.211, Culture=neutral, PublicKeyToken=null" has no implementation.` (translated from German)

I'm using the nuget package of the SQLite scrobbler but I already tried to build it myself.

### PR DESCRIPTION
**Pull request by rikkit**
- match Json.Net and Microsoft.Net.Http with Inflatable.Lastfm

Closes #115 
Closes #122

### CODE REVIEW

**Comment by rikkit** [comment]
@coczero could you check out [this package](https://ci.appveyor.com/project/rikkit/lastfm/build/artifacts) and see if it works for you re #122? Cheers

**Comment by coczero** [comment]
@rikkit The TypeLoadException is gone, but when I try to GetCachedAsync I get the following error: `Method not found: Int32 SQLite.SQLiteConnection.CreateTable(SQLite.CreateFlags)`

**Comment by rikkit** [comment]
What package of `sqlite-net-pcl` is installed in your solution? I've set the dependency to `1.4.118` but when testing it VS sometimes installed an older version - not sure why.

**Comment by rikkit** [comment]
@coczero I think I may have sent you to the wrong package version - [https://ci.appveyor.com/project/rikkit/lastfm/build/1.1.999.346/artifacts](this is the correct link) (build 1.1.999.346)

**Comment by coczero** [comment]
Yea looks like it works. This might be interesting for you - I had `sqlite-net-pcl` version `1.5.166-beta` installed. Which worked so far but stopped working now for some reason.

**Pull request merged**
