### PR TITLE
Update LastResponseStatus and fix unit tests

### PR DESCRIPTION
**Pull request by th0mk**
I ordered them, added some info for error code 29 and added error code 17.

This fixes issue #150.

I've also excluded the sensitive integration tests from the build pipeline. While these are useful, they're very error-prone and should not break a build.

### CODE REVIEW

**Comment by th0mk** [comment]
@rikkit why was this closed?

**Comment by rikkit** [comment]
My bad - I'm migrating the CI to GitHub Actions instead of AppVeyor and I renamed the `master` branch to `next`, deleting `master`. It closed the open PRs. I've reinstated `master` for now and will reopen these PRs - I'm hoping to review and merge them soon :)

**Comment by th0mk** [comment]
Changed the target branch to `next`

**Comment by th0mk** [comment]
I messed up trying to remove my changes to the build pipeline (that you already fixed in your new commits anyway) 🤦‍♂️ and merging `next` to my branch and decided it would be easier to just make a new PR for a small change like this 

Please check out my new pull request #162

**Pull request closed without merging**
