### PR TITLE
Statically expose the api method name corresponding to a Command

### PR DESCRIPTION
**Pull request by yaurthek**
Sorry for the big pull request. I tried to be very careful to keep changes to a minimum, and thoughtful about where to put them.

This fixes bug #71 by statically exposing the api method name corresponding to a Command. This is achieved using a custom attribute taking the method name as a parameter.

In order to avoid duplicating the api method names, I generated a static class full of constants containing said method names, and used these constants both for the custom attributes and for the `Method` property of each Command.

Doing so, I also made the `Method` property `abstract` and read-only, since there is no need to set its value in the Command constructors anymore.

I also added a unit test checking for all Commands to have the custom `ApiMethodName` attribute, and updated the progress reporter code to use these attributes.

### CODE REVIEW

**Comment by rikkit** [comment]
Hey this is cool.

It's a shame there's no such thing as static interfaces in C#, Attributes are a decent workaround though. I'm not too keen on the constants file but I can't think of an alternative. I wonder if the attributes and constants can be automatically generated on compile using the namespace and class name of the command? I don't know enough about templating to do that, though.

Could you add a note to the contributing documentation so that people know what they have to do when they add a command? Is it just a case of adding the attribute and constant?

**Comment by yaurthek** [comment]
Yeah, the constants file is not that nice, I agree.
I can't think of a good way to generate the attributes and/or constants from a template. Do you have something in mind? Something using t4 templates and partial classes might work, but I'm not sure it would be better...

There is another way I pondered: the api methods names could be defined directly on the attributes rather than in a constants file, and the `Method` property could use this attribute to get its value. This behaviour could be implemented in the base class, so that only the attribute would be required on the derived commands.
Pro: this solution would have the advantages of both making the constants file useless, and the attribute even more useful, since it would be the only source of the actual data (the api method name).
Con: having to get the custom attribute value in the `Method` getter would not be as efficient, but this could be mitigated with caching...

What do you think? Writing about it, this idea seems more interesting than I first thought.

Regarding the documentation, yes, I will add a note. Currently, it's just a matter of adding the attribute with the right constant, and implementing the `Method` property with the same constant. Only the attribute would be necessary if we go the way I suggested above.

**Comment by rikkit** [comment]
Yeah it would have been T4 + partial templates, no runtime penalty but annoying to maintain.

Something like this?

```
[ApiMethodName("album.getShouts")]
public class GetShoutsCommand { 
  string MethodName {
    get { 
      var attribute = (ApiMethodNameAttribute) Attribute.GetCustomAttribute(this.GetType(), typeof (ApiMethodNameAttribute));
      return attribute.Text;
    }
 }
``` 

That's a bit cleaner and will be easier to maintain. I think in this case the maintenance issue is more important than performance, and if I'm reading [this](https://msdn.microsoft.com/en-us/library/71s1zwct%28v=vs.110%29.aspx) right then reflection isn't used?

**Comment by yaurthek** [comment]
Yes, something like this. Except the `Method` property would only be defined in the base class.
I'm not sure about whether this method uses reflection or not, but in any case, it's certainly less efficient than accessing a constant.

Doing a quick and dirty benchmark, it seems to be two to four orders of magnitude slower. (in Debug vs Release mode)
It sounds like a lot, but we have to keep in mind that accessing a constant is probably among the most optimized thing a program can do...

For a network related Api, this will not be the bottleneck anyway.

**Comment by rikkit** [comment]
Looks good to me :+1:

**Comment by yaurthek** [comment]
Thank you :)

**Pull request merged**
