### PR TITLE
add Wiki to LastAlbum

### PR DESCRIPTION
**Pull request by dogguts**
add a "Wiki" property to LastAlbum (similar to "Bio" property on LastArtist)

### CODE REVIEW

**Comment by rikkit** [comment]
Thanks for this @dogguts ! Really sorry I haven't had time to look at this recently. It looks like the failures are caused by #146, I suppose I need to get back to this project and solve those.

**Comment by tolbxela** [comment]
@rikkit it looks for me like you don't have time for this project anymore. This one is about one year old. :-)

Would you like someone to help you with the project? 
I am developing right now some service with Last.fm connection and will be using your library a lot.
So, I could take care of some issues or pull requests in the project. 
What do you think about it?

**Review by rikkit — APPROVED** [review]
Thanks @dogguts! Sorry for the extreme delay in merging this.

**Comment by rikkit** [comment]
This is merged into `next` in 9035db05e857acda5b873258680d31cefc84be5b and will go out in v1.3.0.

**Pull request closed without merging**
