### PR TITLE
  Batch scrobbling and Scrobbler classes

### PR DESCRIPTION
**Pull request by rikkit**
Tracking issue for the new auto-caching + batching scrobbler

TODO
- [x] Base Scrobbler classes
- [x] SQLite Scrobbler class
- [x] Tests
- [x] Support multiple scrobbles on ScrobbleCommand
- [x] Batch up scrobbles in ScrobblerBase
- [x] Test batching and caching in unit tests
- [x] Remove extra nugets from SQLite lib
- [x] SQLite nuget package

### CODE REVIEW

**Comment by rikkit** [comment]
@zumicts yo. Do you think this pattern makes sense for you? The intention is that this feature (batching + caching) can be integrated in pretty much one line of code. The core includes a basic non-caching scrobbler (Scrobbler.cs), then scrobblers that use database packages can be distributed separately (the SQLiteScrobbler class in this PR will be distributed in ```Inflatable.Lastfm.SQLite``` for example).

Theoretical code:
```c#
_scrobbler = new SQLiteScrobbler(auth, databaseFile);
var response = _scrobbler.ScrobbleAsync(track.AsScrobble(DateTimeOffset.Now));

// if _scrobbler.CacheEnabled == true then response.Status will be LastResponseStatus.Cached or LastResponseStatus.CacheFailed, otherwise will be the status of the internal scrobble HTTP request
```

Related issue; I notice in Audiotica you have wrapped calls to the SDK in extra service classes, I'd like for that to be unnecessary if possible to reduce lines of code. So you'd DI ITrackApi directly. Would like your thoughts on that too.

**Comment by zumicts** [comment]
I think it makes sense, follows the SOLID pattern and in the future it makes it easier to implement other cache scrobblers.

Yeah, in Audiotica all the related class I use for last.fm are injected.

**Comment by rikkit** [comment]
Good to hear. Feature should be in master in the next couple days. :+1: 

> Yeah, in Audiotica all the related class I use for last.fm are injected.

I was talking about [IScrobblerService specifically](https://github.com/zumicts/Audiotica/blob/2ed42e2fad83168f8005bd3efcb281bb1e267f1b/Audiotica.Data/Service/Interfaces/IScrobblerService.cs). Having a single class to DI is definitely better than seven; does this do anything special? If not we can make something like it in Core.

**Comment by zumicts** [comment]
Oh, yeah it is definitely better to have one class that interacts with the api.  The class does not implement anything special.  Actually, I think it is using my credential helper class for storing username and password.

**Comment by rikkit** [comment]
So I'm thinking of abusing properties a bit and making a super-api class which composes the existing ones.

```
var lastApi = new SuperLastApi(auth, httpclient, scrobbler);

lastApi.Track.LoveAsync();
lastApi.User.GetTopTracksAsync();
lastApi.Artist.GetInfoAsync();
lastApi.Scrobbler.ScrobbleAsync();
```

This'd be flexible to both approaches whilst keeping the codebase tidy. It mirrors the api method names nicely too.

**Comment by zumicts** [comment]
That seems like a nice way of doing it.  Would you use DI,  or do some lazy loading like:

    public Auth Auth
    {
          get
          {
                    return _auth ?? (_auth = new Auth());
          }
    }

**Comment by rikkit** [comment]
I don't think it's worth implementing lazy loading since the Super API class* will only ever hold around 10 object references. The API classes themselves don't store any references, apart from LastAuth (strings and UserSession), and HttpClient if that is provided.

```
public SuperLastApi(string key, string secret, HttpClient httpClient = null, IScrobbler scrobbler = null)
{
    var client = httpClient ?? new HttpClient(); // TODO copy options from command base
    var auth = new LastAuth(key, secret, client);
    Auth = auth;
    Scrobbler = scrobbler ?? new Scrobbler(client);
    Track = new TrackApi(client);
    Album = new AlbumApi(client);
    Artist = new ArtistApi(client);
    Library = new LibraryApi(client);
    // etc.
}
```

**Comment by rikkit** [comment]
> All though maybe we can break the cache functionality away from the Scrobbler class and just have something like Scrobbler.SetCache(IScrobblerCache:cache) or pass it in the constructor (more DI friendly).

Didn't see this edit earlier.

This depends on whether there are other kinds of things we can do with a database in the SDK; ```ILastDbProvider``` and ```LastSQLiteDbProvider``` will definitely be the way to go if so; right now though all I can think of is error logging, which I don't want to implement in this release (0.2 is already way overdue lol). I think the current derived class approach is friendly enough to both DI and non-DI apps for now and can always revisit the issue in the future.

**Comment by zumicts** [comment]
I guess you're right but should it implement `IDisposable` because of the HttpClient?

Ok, let's keep what we have and improve as we go, after all this is just 0.2 and we have a long way to 1.0 :laughing:

**Comment by zumicts** [comment]
Now that I think of it, all commands should be disposable since each one is using an `HttpClient` but in the `SuperLastApi` we will only disposed of the client that was passed to each command.

**Comment by rikkit** [comment]
> I guess you're right but should it implement IDisposable because of the HttpClient (don't want a memory leak)?

Yuuuuuuup.

> Now that I think of it, all commands should be disposable since each one is using an HttpClient but in the SuperLastApi we will only disposed of the client that was passed to each command.

#41 covers this, commands created inside a *Api class will use the same HttpClient. *Api classes should be disposable though. Added a note to this issue

**Pull request merged**
