### PR TITLE
Fixed: Nuget Package Build, Artifacts

### LINKED ISSUE #107: Nuget packages not being created properly on AppVeyor
https://ci.appveyor.com/project/rikkit/lastfm/build/1.0.999.312

```
pushd .nuget
.\pack.ps1 -versionSuffix prerelease
Exception calling "GetAssemblyName" with "1" argument(s): "Could not load file or assembly 'IF.Lastfm.Core.dll' or one of its dependencies. The system cannot find the file specified."
At C:\projects\lastfm\.nuget\pack.ps1:22 char:1
+ $version = [System.Reflection.AssemblyName]::GetAssemblyName($dllPath ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException
 
Setting Inflatable.Lastfm .nuspec version tag to ..-prerelease
Attempting to build package from 'Inflatable.Lastfm...-prerelease.compiled.nuspec'.
NuGet.exe : '..-prerelease' is not a valid version string.
At C:\projects\lastfm\.nuget\pack.ps1:14 char:2
+     & $root\.nuget\NuGet.exe pack "$root\.nuget\$nuspecname.$versionS ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ('..-prerelease'...version string.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Parameter name: version
Setting Inflatable.Lastfm.SQLite .nuspec version tag to ..-prerelease
Attempting to build package from 'Inflatable.Lastfm.SQLite...-prerelease.compiled.nuspec'.
NuGet.exe : '..-prerelease' is not a valid version string.
At C:\projects\lastfm\.nuget\pack.ps1:14 char:2
+     & $root\.nuget\NuGet.exe pack "$root\.nuget\$nuspecname.$versionS ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ('..-prerelease'...version string.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Parameter name: version
popd
cp .\.nuget\*.nupkg .
Collecting artifacts...
No artifacts found matching 'src\IF.Lastfm.Core\bin\Release\IF.Lastfm.Core.dll' path
No artifacts found matching 'src\IF.Lastfm.SQLite\bin\Release\IF.Lastfm.SQLite.dll' path
No artifacts found matching '*-prerelease.nupkg' path
Build success
```

### PR DESCRIPTION
**Pull request by Qstick**
Fixes #107

### CODE REVIEW

**Comment by rikkit** [comment]
Hi @Qstick thank you so much for the PR! I am not in the .Net world much right now, so I am glad the existing build process an be made to work with Nuget 3.

I noticed [this message](https://ci.appveyor.com/project/rikkit/lastfm/build/1.0.999.322#L443) in the build logs:

```
WARNING: 1 issue(s) found with package 'Inflatable.Lastfm'.
Issue: Invalid framework folder.
Description: The folder 'netstandard1.1' under 'lib' is not recognized as a valid framework name or a supported culture identifier.
```

From a quick search it seems like the Appveyor config needs to be updated [in some way](https://github.com/appveyor/ci/issues/888). Have you tried using the package generated by the CI build in a project? Just wondering if the message is a problem or not.

**Comment by Qstick** [comment]
I have not tried to use in a project yet, let me investigate the test further tonight.

**Comment by Qstick** [comment]
@rikkit seems the version of nuget you had packaged with lastfm was pre-3.0. Updated the packaged version to 3.5.0 which recognizes netstandard1.1 as a valid target framework (https://docs.microsoft.com/en-us/nuget/reference/target-frameworks) did the trick. 

On another note you have the SQLite package setup to go into a `lib\portable-win8+net45+wp8+wpa81` directory in the nuget package, should this also be netstandard1.1?

**Comment by rikkit** [comment]
Thanks @Qstick! On the SQLite package, yeah it should - but need to check whether sqlite-net-pcl has a netstandard package now. If I remember right it didn't at the time I originally set up netstandard.

**Pull request merged**
