### PR TITLE
Fixed integration tests, bumped test projects up to .NET 6

### PR DESCRIPTION
**Pull request by Sarsoo**
Fixed the integration tests and tested the other projects. Will follow this by repushing the #167 to retest

### CODE REVIEW

**Comment by rikkit** [comment]
Hey @Sarsoo . changes look fine, thanks!. But I need to figure out why checks aren't running on this branch. Any ideas?

**Comment by Sarsoo** [comment]
That's odd, I had assumed it was a security thing because I changed the actions. When I Google it, branch protection rules seem to keep coming up, [community thread](https://github.community/t/github-actions-some-checks-haven-t-completed-yet-on-pr/155306), [docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule)

**Comment by rikkit** [comment]
Have looked a bit into it, I think you may need to go to your fork of this repo and enable actions on it. Then you may need to push again to this branch to trigger the action... 🤔

**Comment by Sarsoo** [comment]
I have actions enabled on my fork. On checking, however I did notice this setting

image

With a link to [this bit of the docs](https://docs.github.com/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) which suggests that first time collaborators need approval. I can try pushing a dummy commit to see if it'll get it moving, presumably there's no button to approve the actions on the PR from your side?

**Comment by rikkit** [comment]
This is what I see 

image

Yeah I was wondering about the Actions config. The workflow is only set to run on `push`. I'm not sure what that should be changed to in order to run when a PR is opened from a forked repo. Can you try pushing that dummy commit?

Cheers

**Comment by Sarsoo** [comment]
Coming back to this, I was hoping to see if we could move this forward. The blocker currently is the CI not running so I'm going to close this PR and open a new one to see if that can jump start it

**Pull request closed without merging**
