### PR TITLE
Add new optional parameters to get recent tracks request

### LINKED ISSUE #113: User.getRecentScrobbles is missing the "To" and "Extended" parameter
According to [the api](https://www.last.fm/api/show/user.getRecentTracks) these parameters are optional for the command, but I think they would be really helpful.

### PR DESCRIPTION
**Pull request by L-Dogg**
Trying to fix #113 . I have also modified the Page property, so that it defaults to 1 (as in the API's description) and added an unit test to test the extended response parsing.

### CODE REVIEW

**Comment by klinge** [comment]
The "extended" and "to/from" parameters would be nice to have in User.GetRecentTracks. Found myself wanting the "extended" response today.. :) I only see two problems with this PR: 

1. since porting the test projects to dotnet core was done after this PR some changes to the unit tests need to be done

1. In the User/GetRecentTracksCommand.cs I see a "bool extended" attribute. But I can¨t see this being used to add "extended=1" to the Parameters list. If I don't miss anything this would need to be fixed before getting "extended" to work properly. 

Is @L-Dogg still here?

**Comment by L-Dogg** [comment]
@klinge I'll try to look at the two issues you mentioned

**Comment by klinge** [comment]
Great! 

Main change in order to make the tests run under dotnet core is that the resource files are handled differently and the "resource designer files" from Visual Studio are no longer used. 

In order for a end-user of the library to be able to use the added parameters in the GetRecentTracksCommand, I think you would need to add the new parameters to the GetRecentScrobbles function too (this is the api function calling the GetRecentTracksCommand). The interface for this is in IUserApi.cs and the implementation is in UserApi.cs.

**Comment by L-Dogg** [comment]
@klinge Please take a look at #144 - I had some issues merging fresh master into this stale branch, hence the new PR.

**Pull request closed without merging**
